### ISSUE TITLE
GVFS-bin

### ISSUE THREAD

**Issue by ti-ago** [costales/folder-color#16]
It still requires gvfs-bin for folder-color-nemo

**Comment by pietryszak** [comment]
Gvfs-bin is not avaible for 22.04, so I unable to install :/

**Comment by costales** [comment]
Hi,
I installed it in 22.04.
Could you tell me more? Distro, file browser and PPA or not?
Thanks

**Comment by pietryszak** [comment]
> Hi, I installed it in 22.04. Could you tell me more? Distro, file browser and PPA or not? Thanks

Ubuntu 22.04.1 LTS Server version. I install all packages to create my own i3-gaps. Is installed by ansible script.
```

      - name: Add nemo file manager ppa
        ansible.builtin.shell: |
          add-apt-repository --yes ppa:costales/folder-color


      - name: Install Nemo folder colors menu
        ansible.builtin.apt:
          pkg: 
            - folder-color-nemo
          update_cache: yes  
```

![image](https://user-images.githubusercontent.com/45850093/195910937-f5aa0fb1-e6e2-4cc8-8080-1e0b86a98f26.png)
